easier to use

diff --git a/spindra_run b/spindra_run
--- a/spindra_run
+++ b/spindra_run
@@ -1,19 +1,46 @@
 #!/bin/bash
 
+OPENVPN_CONFIG=$1
+
+if [ -z $OPENVPN_CONFIG ]; then
+    sudo docker run -dit --rm --name spindra -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v $HOME/Downloads/spindra:/data wh1t3f0x/spindra
+    exit
+fi
+
+if ! test -f "$OPENVPN_CONFIG"; then
+    echo -e "$OPENVPN_CONFIG not a file"
+    exit
+fi
+
 # Verify sudo cache / create it
 sudo -v
 
-# Build
-sudo docker build . -t spindra
+function start_image {
 
-# Launch spindra
-sudo docker run -dit --rm \
-    --name spindra \
-    -e DISPLAY=$DISPLAY \
-    -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
-    -v $HOME/Downloads/spindra:/data \
-    --net=container:openvpn \
-    wh1t3f0x/spindra:latest
+    sudo docker run -dit --rm \
+        --name spindra \
+        -e DISPLAY=$DISPLAY \
+        -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
+        -v $HOME/Downloads/spindra:/data \
+        --net=container:openvpn \
+        wh1t3f0x/spindra
+}
 
-# Get in container
-sudo docker exec -it spindra bash
+if [ "$(docker ps -a --format {{.Names}} --filter 'name=openvpn')" == "openvpn" ]; then
+    start_image
+    exit
+fi
+
+docker pull -q quay.io/0xcaff/openvpn-client 2>&1 >/dev/null
+docker run -dit --rm --cap-add=NET_ADMIN --device /dev/net/tun --name openvpn -v $OPENVPN_CONFIG:/vpn/config/config.ovpn quay.io/0xcaff/openvpn-client 2>&1 >/dev/null
+
+sleep 30
+
+# Running ?
+if [ "$(docker ps -a --format {{.Names}} --filter 'name=openvpn')" != "openvpn" ]; then
+    echo -n "Failed to start VPN. Check $OPENVPN_CONFIG, /dev/net/tun, or possible need a reboot."
+    echo -n " You can also try adding: \n pull-filter ignore \"ifconfig-ipv6 \"\npull-filter ignore \"route-ipv6 \"\n to your config."
+    exit 1
+fi
+
+start_image
